name: intl_phone_field_extended
description: A specialized Flutter TextFormField designed for seamless input of international phone numbers, complete with country code selection.
version: 3.3.2
homepage: https://github.com/ArmenKocharyan/intl_phone_field_extended

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.17.12

flutter:
  assets:
    - assets/flags/
